### ISSUE TITLE
Best way to find a solution about the new Plexure system

### ISSUE THREAD

**Issue by agostinofiscale** [0xf77/mcfux#1]
Hi! 
I like this project and I did something like this some weeks ago just for fun and to eat some good calories at McDonald's.
I would like to help the project finding a solution (also if I'm learning how to use GitHub recently) and i want to ask if you have any advices for me. Is decompiling the app the best solution to find the algorithm behind the app that make the "**x-plexure-api-key**"? What I found is that app check if the key is already uses for something and if It is then make another one. Now I should probably check what It does and I have think that the best solution would be to debug the app but I'm not sure about this.

**Comment by aeerso** [comment]
Hi,
I think the best solution is to debug the app while running, setting a breakpoint on the encryption function and comparing inputs/outputs. I also think that the encryption is called multiple times but essentially is needed to compare the id with a timestamp. 
Also you should check the /keys endpoint, as it could be useful.
