### ISSUE TITLE
Cannot generate valid Plexure key

### ISSUE THREAD

**Issue by sn0wst0rm** [0xf77/mcfux#3]
Hello, I discovered yesterday this project and I'm trying to figure out your work. As far as I got by now,  I understood that the objects needed for a successful authentication on the server I need the auth key got from https://config-api-dot-prd-euw-gmal-mcdonalds.appspot.com/api/config/v1/keys and the uid generated by the code of @kaaetech.

The issue I'm facing now is how to get `NDM4MzU4MDk1NjA5NDI1NDk2NDEzMjkyOTkwMTIzNDg6NzIwMzl5eTc5NDBkYjkycnp6ZW4xNXFpYnZlOTRsbGtjejY3bmJ6eXlsNGU5ZTlhaHpvNGpzdzRyMjlsOWlvMQ` which is the key needed to get the json from the server, containing the various auth_key values.

As @ddekus suggested, I digged in the app's data folder and found the VMOB_PREFERENCES.xml file, which contains two significant values: `API_KEY_ENCRYPTED_KEY=i9yF9/V6FWJcwCWrs+JJuXNTZiy/+dG6pZwv7OCdbziuGzYymQchbdGJD+MNdBU1b7YfqyRmqPVUBFIlKp6JcM8iLDujIQ9S8OeySRbm6i3zv9z+yJDwJA==` (this one changes with time) and AUTH_KEY which contains one of the keys from https://config-api-dot-prd-euw-gmal-mcdonalds.appspot.com/api/config/v1/keys.

I noticed that this key was not listed in the json that the server gives me when using `NDM4MzU4MDk1NjA5NDI1NDk2NDEzMjkyOTkwMTIzNDg6NzIwMzl5eTc5NDBkYjkycnp6ZW4xNXFpYnZlOTRsbGtjejY3bmJ6eXlsNGU5ZTlhaHpvNGpzdzRyMjlsOWlvMQ` (in the exact moment) so I guess that these keys changes for each account.

The `API_KEY_ENCRYPTED_KEY` value does not seem to be the key needed to get a response from the server since it contains `/` illegal for web URLs and it is not the same length.

Scrolling down issue #2, I read that @0xf77 tried to figure out how to generate a valid `x-plexure-api-key`. The function that create this string is in co/vmob/sdk/network/d.class and calls a static function (`ConfigurationUtils.c()`) and then appends to it a timestamp. This string is then passed to the a() function in /co/vmob/sdk/network/b.class:
```
public static String a(String paramString1, String paramString2)
  {
    try
    {
      byte[] arrayOfByte = new byte[8];
      new SecureRandom().nextBytes(arrayOfByte);
      paramString2 = new PBEKeySpec(paramString2.toCharArray(), arrayOfByte, 100, 384);
      paramString2 = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1").generateSecret(paramString2).getEncoded();
      SecretKeySpec localSecretKeySpec = new SecretKeySpec(Arrays.copyOfRange(paramString2, 0, 32), "AES");
      Cipher localCipher = Cipher.getInstance("AES/CBC/PKCS7Padding");
      localCipher.init(1, localSecretKeySpec, new IvParameterSpec(Arrays.copyOfRange(paramString2, 32, 48)));
      paramString1 = localCipher.doFinal(paramString1.getBytes("UTF-8"));
      paramString2 = new ByteArrayOutputStream();
      paramString2.write(paramString1);
      paramString2.write(arrayOfByte);
      paramString1 = Base64.encodeToString(paramString2.toByteArray(), 0).replace("\n", "").replace(" ", "");
      return paramString1;
    }
    catch (Exception paramString1)
    {
      paramString1.printStackTrace();
    }
    return null;
  }
```
along with a second string built using co.vmob.android.sdk., the android_id identifier or the phone IMEI and then ciphered with DES in
```
private static String a(String paramString)
  {
    try
    {
      localObject = new DESKeySpec("co.vmob.sdk.android.encrypt.key".getBytes("UTF8"));
      localObject = SecretKeyFactory.getInstance("DES").generateSecret((KeySpec)localObject);
      paramString = paramString.getBytes("UTF8");
      Cipher localCipher = Cipher.getInstance("DES");
      localCipher.init(1, (Key)localObject);
      paramString = Base64.encodeToString(localCipher.doFinal(paramString), 8).replace('\n', '_');
      return paramString;
    }
```

My questions are now: is `x-plexure-api-key` the key needed to get from the server the AUTH_KEY or is this something else?

I also read the final code by @kaaetech
```
package com.company;

import javax.crypto.Cipher;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import java.io.ByteArrayOutputStream;
import java.security.SecureRandom;
import java.util.Arrays;
import java.lang.StringBuilder;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.*;


public class b {
    public static String a(String str, String str2) {
        try {
            byte[] bArr = new byte[8];
            new SecureRandom().nextBytes(bArr);
            byte[] encoded = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1").generateSecret(new
PBEKeySpec(str2.toCharArray(), bArr, 100, 384)).getEncoded();
            SecretKeySpec secretKeySpec = new SecretKeySpec(Arrays.copyOfRange(encoded, 0, 32), "AES");
            Cipher instance = Cipher.getInstance("AES/CBC/PKCS5Padding");
            instance.init(1, secretKeySpec, new IvParameterSpec(Arrays.copyOfRange(encoded, 32, 48)));
            byte[] doFinal = instance.doFinal(str.getBytes("UTF-8"));
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            byteArrayOutputStream.write(doFinal);
            byteArrayOutputStream.write(bArr);
	    return Base64.getEncoder().encodeToString(byteArrayOutputStream.toByteArray());
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public static void main(String[] args){
         String auth_key = "d4eee068-272a-4aec-9681-5e16dcef6fbd";
         SimpleDateFormat var0 = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSSSSS'Z'", Locale.US);
         var0.setTimeZone(TimeZone.getTimeZone("UTC"));
         String payload = auth_key+"|"+var0.format(new Date(Long.valueOf((new Date()).getTime()-1000*10*60))); //random key from /keys endpoint
         //((StringBuilder)localObject2).append("|");
         String outputVal = a(payload, args[0]); //x-vmob-uid
         System.out.println(outputVal.replace("\n", "").replace(" ", ""));
}
}
```
which should generate a plexure key. I tried to generate it but then I don't understand if it stands for the `x-vmob-uid` needed in the header, and I am not able to get any valid account token from the server.

Could you please help me with this?
Thank you!

**Comment by kaaetech** [comment]
Don't go through all this hassle. Just run my code
 ```
String outputVal = a(payload, args[0]); //x-vmob-uid
```

takes in a command line argument. x-vmob-uid is just a uuid4, make one up and include it as a header when doing the request.

run code like this: java b.java <uuid4here>

**Comment by sn0wst0rm** [comment]
@kaaetech I tried your code using a random uuid4`5df05df4-a49d-47e7-8ab3-c15799dc25fd` and I got this x-vmob-uid: `fst8OmE0e7fmjZ+59xtZnR7FEoRbJ+Gb30goR4h/p7B5gP/Q5tO1y8k0i8lAMQhpmwJthgMw1oifWs3HI5z1cpcKBrQ//n2f0xsigGuc3KfXeJvEPBv6PA==`

Using as x-vmob-authorization the key `546cd253-ea12-5b74-1354-183a4a050033` got from https://config-api-dot-prd-euw-gmal-mcdonalds.appspot.com/api/config/v1/keys?key=NDM4MzU4MDk1NjA5NDI1NDk2NDEzMjkyOTkwMTIzNDg6NzIwMzl5eTc5NDBkYjkycnp6ZW4xNXFpYnZlOTRsbGtjejY3bmJ6eXlsNGU5ZTlhaHpvNGpzdzRyMjlsOWlvMQ==

The final headers are:
```
headers = {
            'x-vmob-location_accuracy': '',
            'x-vmob-beacons': '',
            'Accept': 'application/json',
            'x-vmob-device_os_version': '',
            'x-vmob-device_type': 'a',
            'x-vmob-uid': 'fst8OmE0e7fmjZ+59xtZnR7FEoRbJ+Gb30goR4h/p7B5gP/Q5tO1y8k0i8lAMQhpmwJthgMw1oifWs3HI5z1cpcKBrQ//n2f0xsigGuc3KfXeJvEPBv6PA==',
            'x-vmob-cost-center': 'merchantId587',
            'x-vmob-authorization': '546cd253-ea12-5b74-1354-183a4a050033',
            'x-vmob-device_timezone_id': 'GMT',
            'x-vmob-device_screen_resolution': '',
            'x-vmob-mobile_operator': self.vmob_mobile,
            'Authorization': self.random_starter_bearer,
            'x-vmob-device': self.vmob_device,
            'x-vmob-location_longitude': '',
            'x-vmob-location_latitude': '',
            'x-vmob-sdk_version': '4.36.3',
            'x-vmob-device_network_type': '',
            'Accept-Language': 'it-IT',
            'x-vmob-device_utc_offset': '-0:00',
            'x-vmob-application_version': '2530',
            'Content-Type': 'application/json',
            'User-Agent': 'GMAL/1.2.18 (iPhone; iOS 12.1.1; Scale/3.00)',
            'Host': 'con-west-europe-gma.vmobapps.com',
        }
```

and the post request is sent to https://con-west-europe-gma.vmobapps.com/v3/emailRegistrations

The response is still an 403 error

**Comment by sn0wst0rm** [comment]
Moreover I am trying to understand how you got the `NDM4MzU4MDk1NjA5NDI1NDk2NDEzMjkyOTkwMTIzNDg6NzIwMzl5eTc5NDBkYjkycnp6ZW4xNXFpYnZlOTRsbGtjejY3bmJ6eXlsNGU5ZTlhaHpvNGpzdzRyMjlsOWlvMQ==` key needed to get updated x-vmob-authorization keys.

I cannot generate another valid one in any way nor I can find it on the app data. Do you have any clue about this?

**Comment by kaaetech** [comment]
It's not a vmob uid you get, it's a plexure key. What you put in, the uuid; is the vmob uid.
NDM4MzU4MDk1NjA5NDI1NDk2NDEzMjkyOTkwMTIzNDg6NzIwMzl5eTc5NDBkYjkycnp6ZW4xNXFpYnZlOTRsbGtjejY3bmJ6eXlsNGU5ZTlhaHpvNGpzdzRyMjlsOWlvMQ is the get parameter in the config / keys request, it is BASE64 encoded and is hardcoded into the app.

headers = {
            'x-vmob-location_accuracy': '',
            'x-vmob-beacons': '',
            'Accept': 'application/json',
            'x-vmob-device_os_version': '',
            'x-vmob-device_type': 'a',
            'x-vmob-uid': '**vmob uuid4**,
            'x-plexure-api-key': '**output of my script**',
            'x-vmob-cost-center': 'merchantId587',
            'x-vmob-device_timezone_id': 'GMT',
            'x-vmob-device_screen_resolution': '',
            'x-vmob-mobile_operator': self.vmob_mobile,
            'Authorization': self.random_starter_bearer,
            'x-vmob-device': self.vmob_device,
            'x-vmob-location_longitude': '',
            'x-vmob-location_latitude': '',
            'x-vmob-sdk_version': '4.36.3',
            'x-vmob-device_network_type': '',
            'Accept-Language': 'it-IT',
            'x-vmob-device_utc_offset': '-0:00',
            'x-vmob-application_version': '2530',
            'Content-Type': 'application/json',
            'User-Agent': 'GMAL/1.2.18 (iPhone; iOS 12.1.1; Scale/3.00)',
            'Host': 'con-west-europe-gma.vmobapps.com',
        }

**Comment by kaaetech** [comment]
Read issue #2, please - everything you want to know is in there.

**Comment by sn0wst0rm** [comment]
@kaaetech 
I've already read it, what I did not understand was the 'x-plexure-api-key' header. I tried with one of the keys got from https://config-api-dot-prd-euw-gmal-mcdonalds.appspot.com/api/config/v1/keys but I got the same error 403.

```
self.plexure_key = "1j1A8PmqpNQQFvDC+6+J1imdP5R1sYD9P6ul44qNCgQdHBOcMxyShSVhEPSvEG605xnUSbDBiehUTaIH5+dOVZSBh84dtAyK1OwRMZE3g72gpXg6GmqYtA=="

        headers = {
         'x-vmob-location_accuracy': '',
         'x-vmob-beacons': '',
         'Accept': 'application/json',
         'x-vmob-device_os_version': '',
         'x-vmob-device_type': 'a',
         'x-vmob-uid': self.random_uid,
         'x-plexure-api-key': self.plexure_key,
         'x-vmob-cost-center': 'merchantId587',
         'x-vmob-device_timezone_id': 'GMT',
         'x-vmob-device_screen_resolution': '',
         'x-vmob-mobile_operator': self.vmob_mobile,
         'Authorization': self.random_starter_bearer,
         'x-vmob-device': self.vmob_device,
         'x-vmob-location_longitude': '',
         'x-vmob-location_latitude': '',
         'x-vmob-sdk_version': '4.36.3',
         'x-vmob-device_network_type': '',
         'Accept-Language': 'it-IT',
         'x-vmob-device_utc_offset': '-0:00',
         'x-vmob-application_version': '2530',
         'Content-Type': 'application/json',
         'User-Agent': 'GMAL/1.2.18 (iPhone; iOS 12.1.1; Scale/3.00)',
         'Host': 'con-west-europe-gma.vmobapps.com',
        }
```

I used instead the key in your last post in #2 d4eee068-272a-4aec-9681-5e16dcef6fbd which is actually the same as the one I got in /data/data/com.mcdonalds.mobileapp/shared_prefs/VMOD_PREFERENCES.xml.

With this one it worked and I successfully got a token. Once I tried to redeem the coupon though the server told me the offer was already redeemed.

Now my question is: Could the auth_key d4eee068-272a-4aec-9681-5e16dcef6fbd be a const? Since me and you got the same and it is the only working. In this case what is the use of the 10 keys given by https://config-api-dot-prd-euw-gmal-mcdonalds.appspot.com/api/config/v1/keys, as they fail in authenticating.

Regarding `NDM4MzU4MDk1NjA5NDI1NDk2NDEzMjkyOTkwMTIzNDg6NzIwMzl5eTc5NDBkYjkycnp6ZW4xNXFpYnZlOTRsbGtjejY3bmJ6eXlsNGU5ZTlhaHpvNGpzdzRyMjlsOWlvMQ` now I fully understand.

Thank you in advance for helping me getting through this, really appreciated

**Comment by kaaetech** [comment]
You got the part that I can help with working, if you successfully made a request without getting a 403 / Access Denied. The rest is up to you, I don’t encourage you to cheat for free burgers. Keep it educational buddy

**Comment by sn0wst0rm** [comment]
@kaaetech I could't even if wanted, I live in Italy and there's no free burger offers here 😄.
Anyways my purpose is not generate endlessly coupon but it's fully understanding their system.

In fact the part I am now confused about now is, as I said in my previous post, the use of https://config-api-dot-prd-euw-gmal-mcdonalds.appspot.com/api/config/v1/keys request with NDM4MzU4MDk1NjA5NDI1NDk2NDEzMjkyOTkwMTIzNDg6NzIwMzl5eTc5NDBkYjkycnp6ZW4xNXFpYnZlOTRsbGtjejY3bmJ6eXlsNGU5ZTlhaHpvNGpzdzRyMjlsOWlvMQ key, which should give me a valid auth_key to generate a valid plexure key. However none of that works. The only auth_key that the server accepts is the one you put in your code `d4eee068-272a-4aec-9681-5e16dcef6fbd` and it is oddly the same I get in the shared prefs in the app data when ran on the phone.

I tried to go through the app's code but I can't find it hardcoded, nor I can found where the app gets it on a server if it is pulled from a remote source. If this auth_key is the only valid one and it is constant, what is the meaning and the use of the 10 keys the server give back with the request?

**Comment by kaaetech** [comment]
d4eee068-272a-4aec-9681-5e16dcef6fbd is not a AUTH_KEY from the endpoint, it's a hardcoded one from /data/data/com.mcdonalds.mobileapp/shared_prefs/VMOD_PREFERENCES.xml.

NDM4MzU4MDk1NjA5NDI1NDk2NDEzMjkyOTkwMTIzNDg6NzIwMzl5eTc5NDBkYjkycnp6ZW4xNXFpYnZlOTRsbGtjejY3bmJ6eXlsNGU5ZTlhaHpvNGpzdzRyMjlsOWlvMQ is hardcoded too and is a BASE64 value as already mentioned that gives access to another endpoint. I don't yet know the meaning of the 10 keys in JSON format from the /keys endpoint.

**Comment by giacomoferretti** [comment]
You can checkout my repo for a working Plexure key generation [here](https://github.com/giacomoferretti/mcdapi). It's only missing documentation, so you have to read it from the code.
