### ISSUE TITLE
Why i get error 401 when trying get coupon?

### ISSUE THREAD

**Issue by MikeCoder96** [0xf77/mcfux#4]
Hello everyone, I'm working on this source just for fun. After some work I used the code from @kaatech and each time I send request to server I generate a plexure key.
What Is my mistake??

**Comment by MikeCoder96** [comment]
Fixed, the problem is the time in my python code "I have translate the java code in python"

**Comment by bonelesspizza21** [comment]
Could you share the python-translated code? Thanks

**Comment by kaaetech** [comment]
```Python
import subprocess
cmd = "java b.java "+x_vmob_uid
plexure_api_key = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE)
plexure_api_key = str(plexure_api_key).split("stdout=b'")[1].split(r'\n')[0].replace("\n", "").replace(" ", "")
```

for the lazy ones.. @bonelesspizza21

**Comment by MikeCoder96** [comment]
@kaaetech i have worked differently, I have translated all java code you have published to python.

**Comment by giacomoferretti** [comment]
Checkout https://github.com/giacomoferretti/McDonaldsApi

**Comment by giacomoferretti** [comment]
You can checkout my repo for a working Plexure key generation [here](https://github.com/giacomoferretti/mcdapi). It's only missing documentation, so you have to read it from the code.
